# Slicing

In [1]:
import sys
print(sys.version)
import numpy as np
print(np.__version__)

3.9.7 (default, Sep 16 2021, 08:50:36) 
[Clang 10.0.0 ]
1.22.4


In [2]:
np.random.seed(10)

In [3]:
ar = np.arange(12)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
ar2 = np.random.randint(12, size = 12).reshape([3,4])

In [5]:
ar2

array([[ 9,  4,  0,  1],
       [11,  9,  0,  1],
       [10,  8,  9,  0]])

In [6]:
ar[0]

0

In [7]:
ar[5]

5

In [8]:
ar[5:]

array([ 5,  6,  7,  8,  9, 10, 11])

In [9]:
ar[:5]

array([0, 1, 2, 3, 4])

In [10]:
ar[2:8:2]

array([2, 4, 6])

In [11]:
ar[:-1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
ar[:-5]

array([0, 1, 2, 3, 4, 5, 6])

In [13]:
ar[-1:-8:-2]

array([11,  9,  7,  5])

In [14]:
ar2

array([[ 9,  4,  0,  1],
       [11,  9,  0,  1],
       [10,  8,  9,  0]])

In [15]:
ar2[:,1:3] # row, column

array([[4, 0],
       [9, 0],
       [8, 9]])

In [16]:
ar2[1:3,:]

array([[11,  9,  0,  1],
       [10,  8,  9,  0]])

In [17]:
ar2[::2,::2]

array([[ 9,  0],
       [10,  9]])

In [18]:
ar2[1:3:2,1:3:2]

array([[9]])

## Combining

In [19]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
ar2

array([[ 9,  4,  0,  1],
       [11,  9,  0,  1],
       [10,  8,  9,  0]])

In [21]:
ar2.flatten()

array([ 9,  4,  0,  1, 11,  9,  0,  1, 10,  8,  9,  0])

In [22]:
np.vstack([ar, ar2.flatten()])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 9,  4,  0,  1, 11,  9,  0,  1, 10,  8,  9,  0]])

In [23]:
ar2

array([[ 9,  4,  0,  1],
       [11,  9,  0,  1],
       [10,  8,  9,  0]])

In [24]:
ar.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
np.vstack((ar.reshape(3,4),ar2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 9,  4,  0,  1],
       [11,  9,  0,  1],
       [10,  8,  9,  0]])

In [26]:
np.hstack((ar, ar2.flatten(), ar))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  9,  4,  0,  1, 11,
        9,  0,  1, 10,  8,  9,  0,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11])

In [27]:
np.hstack((ar.reshape(3,4),ar2))

array([[ 0,  1,  2,  3,  9,  4,  0,  1],
       [ 4,  5,  6,  7, 11,  9,  0,  1],
       [ 8,  9, 10, 11, 10,  8,  9,  0]])

In [28]:
np.vstack(ar for x in range(10))

/var/folders/b2/p1xf076x7h36q6dg3vmqb7wh0000gn/T/ipykernel_12530/3431730501.py:1: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  np.vstack(ar for x in range(10))


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [29]:
(ar for x in range(10))

<generator object <genexpr> at 0x7fb220917890>

In [30]:
np.concatenate((ar, ar2.flatten()))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  9,  4,  0,  1, 11,
        9,  0,  1, 10,  8,  9,  0])

In [31]:
np.concatenate((ar, ar2.flatten()), axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [32]:
np.concatenate(([ar], [ar2.flatten()]), axis = 0)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 9,  4,  0,  1, 11,  9,  0,  1, 10,  8,  9,  0]])

In [33]:
np.concatenate(([ar], [ar2.flatten()])) #0 is default

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 9,  4,  0,  1, 11,  9,  0,  1, 10,  8,  9,  0]])

In [34]:
np.concatenate((ar2, ar2))

array([[ 9,  4,  0,  1],
       [11,  9,  0,  1],
       [10,  8,  9,  0],
       [ 9,  4,  0,  1],
       [11,  9,  0,  1],
       [10,  8,  9,  0]])

In [35]:
np.concatenate((ar2, ar2), axis = 1)

array([[ 9,  4,  0,  1,  9,  4,  0,  1],
       [11,  9,  0,  1, 11,  9,  0,  1],
       [10,  8,  9,  0, 10,  8,  9,  0]])

In [36]:
np.dstack((ar2,ar2))

array([[[ 9,  9],
        [ 4,  4],
        [ 0,  0],
        [ 1,  1]],

       [[11, 11],
        [ 9,  9],
        [ 0,  0],
        [ 1,  1]],

       [[10, 10],
        [ 8,  8],
        [ 9,  9],
        [ 0,  0]]])

## Splitting Arrays

In [37]:
ar3 = np.dstack((ar2,ar2))

In [38]:
ar3

array([[[ 9,  9],
        [ 4,  4],
        [ 0,  0],
        [ 1,  1]],

       [[11, 11],
        [ 9,  9],
        [ 0,  0],
        [ 1,  1]],

       [[10, 10],
        [ 8,  8],
        [ 9,  9],
        [ 0,  0]]])

In [39]:
ar21, ar22 = np.dsplit(ar3, 2)

In [40]:
np.dsplit(ar3,2)

[array([[[ 9],
         [ 4],
         [ 0],
         [ 1]],
 
        [[11],
         [ 9],
         [ 0],
         [ 1]],
 
        [[10],
         [ 8],
         [ 9],
         [ 0]]]),
 array([[[ 9],
         [ 4],
         [ 0],
         [ 1]],
 
        [[11],
         [ 9],
         [ 0],
         [ 1]],
 
        [[10],
         [ 8],
         [ 9],
         [ 0]]])]

In [41]:
ar21

array([[[ 9],
        [ 4],
        [ 0],
        [ 1]],

       [[11],
        [ 9],
        [ 0],
        [ 1]],

       [[10],
        [ 8],
        [ 9],
        [ 0]]])

In [42]:
ar21.reshape(3,4)

array([[ 9,  4,  0,  1],
       [11,  9,  0,  1],
       [10,  8,  9,  0]])

In [43]:
np.dsplit(ar3,2)[0]

array([[[ 9],
        [ 4],
        [ 0],
        [ 1]],

       [[11],
        [ 9],
        [ 0],
        [ 1]],

       [[10],
        [ 8],
        [ 9],
        [ 0]]])

In [44]:
np.squeeze(np.dsplit(ar3,2)[0])

array([[ 9,  4,  0,  1],
       [11,  9,  0,  1],
       [10,  8,  9,  0]])

In [45]:
np.hsplit(ar2,2)

[array([[ 9,  4],
        [11,  9],
        [10,  8]]),
 array([[0, 1],
        [0, 1],
        [9, 0]])]

In [46]:
ar2

array([[ 9,  4,  0,  1],
       [11,  9,  0,  1],
       [10,  8,  9,  0]])

In [47]:
np.vsplit(ar2,3)

[array([[9, 4, 0, 1]]), array([[11,  9,  0,  1]]), array([[10,  8,  9,  0]])]

In [48]:
np.vsplit(ar2.T, 2)

[array([[ 9, 11, 10],
        [ 4,  9,  8]]),
 array([[0, 0, 9],
        [1, 1, 0]])]

In [49]:
ar2.T

array([[ 9, 11, 10],
       [ 4,  9,  8],
       [ 0,  0,  9],
       [ 1,  1,  0]])