# Arrays

available in numpy, not in base python

optimized for computational performance

In [3]:
import numpy as np

In [7]:
x = np.arange(0,20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
x[2] = 12
x

array([ 0,  1, 12,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
x.dtype

dtype('int64')

In [14]:
x[10] = 2.5
x

array([ 0,  1, 12,  3,  4,  5,  6,  7,  8,  9,  2, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
x.dtype

dtype('int64')

In [19]:
x.append(3)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [20]:
x.pop()

AttributeError: 'numpy.ndarray' object has no attribute 'pop'

In [22]:
np.random.rand(5,5)

array([[ 0.28276014,  0.88018381,  0.58102812,  0.02343857,  0.84841964],
       [ 0.88801967,  0.57158127,  0.91145584,  0.09428778,  0.61428194],
       [ 0.73304485,  0.00170256,  0.68672751,  0.10220823,  0.75720077],
       [ 0.09778026,  0.04915721,  0.38438673,  0.25923346,  0.47399476],
       [ 0.04693855,  0.49837085,  0.10848638,  0.16377411,  0.34720562]])

In [23]:
np.random.rand(5,5,5)

array([[[ 0.66188253,  0.12675386,  0.38750297,  0.24921162,  0.15688114],
        [ 0.217198  ,  0.3017225 ,  0.09949964,  0.41947062,  0.91954123],
        [ 0.43351182,  0.51929644,  0.49535374,  0.08078497,  0.06326947],
        [ 0.32868138,  0.73254281,  0.14587663,  0.06552111,  0.9308868 ],
        [ 0.27748476,  0.74582307,  0.02280054,  0.02618894,  0.82589316]],

       [[ 0.51827403,  0.26077014,  0.15758162,  0.41501447,  0.83516251],
        [ 0.88300295,  0.6892749 ,  0.59871141,  0.84198891,  0.03309549],
        [ 0.93409542,  0.65632156,  0.54552273,  0.85637874,  0.11629729],
        [ 0.1261468 ,  0.09047905,  0.84518105,  0.1303537 ,  0.93473341],
        [ 0.11717919,  0.42554358,  0.75934619,  0.74181722,  0.38305578]],

       [[ 0.03849241,  0.75487687,  0.67803837,  0.21483806,  0.95371881],
        [ 0.26605138,  0.31415024,  0.19689409,  0.23590772,  0.47029828],
        [ 0.52993089,  0.88757534,  0.49719954,  0.58809578,  0.23275105],
        [ 0.07548245,

In [24]:
np.random?

In [25]:
np.random.randn(20)

array([-1.32984074,  0.4776307 ,  1.08602593,  0.69234314,  0.16542605,
       -1.01743539,  0.22145639, -2.38432311,  1.05996435, -1.60899074,
        0.64176907, -0.32367732, -0.13193928,  0.22247556, -0.09433053,
       -0.01212189, -1.8485733 , -0.25505794,  0.70295112,  0.63812013])

In [26]:
ar = np.random.randn(20)
ar

array([-0.33697566, -2.13735435, -1.1933344 , -0.89469003,  0.72827748,
       -0.46400013,  0.98577774,  0.52251447, -1.73646272,  0.39271555,
       -1.47430241, -0.14397075,  0.24332876, -0.47434338, -0.10057133,
       -1.18293774,  0.5841916 , -0.26492167,  1.73029962,  0.46781063])

In [28]:
ar.mean()

-0.23744743668727269

In [29]:
ar.std()

0.96049279620738237

In [32]:
ar = ar.reshape(5,4)
ar

array([[-0.33697566, -2.13735435, -1.1933344 , -0.89469003],
       [ 0.72827748, -0.46400013,  0.98577774,  0.52251447],
       [-1.73646272,  0.39271555, -1.47430241, -0.14397075],
       [ 0.24332876, -0.47434338, -0.10057133, -1.18293774],
       [ 0.5841916 , -0.26492167,  1.73029962,  0.46781063]])

In [33]:
ar.mean(axis = 0)

array([-0.10352811, -0.5895808 , -0.01042616, -0.24625469])

In [34]:
ar.mean(axis = 1)

array([-1.14058861,  0.44314239, -0.74050508, -0.37863092,  0.62934504])